### PR TITLE
Don't kill `fkill` when killing `node.exe`

### PR DESCRIPTION
**Pull request by yaodingyd**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Tests are failing on Windows.

**Comment by yaodingyd** [comment]
It  looks like ava spawn three node processes on windows:
pids
The current process  also has a parent process which is also a node process.
And it fails at killing the parent process.

**Comment by sindresorhus** [comment]
You can move the test logic into a new fixture file and in the test, just spawn the fixture and check the status. That way it's not affected by how AVA works.

**Comment by yaodingyd** [comment]
Could you show me an example of spawning a fixture?

**Comment by sindresorhus** [comment]
Fixture file:

```js
const originalFkillPid = process.pid;
	if (process.platform === 'win32') {
		await fkill('node.exe');
	} else {
		await fkill('node');
	}

process.exitCode = await processExists(originalFkillPid) ? 10 : 20;
```

And then just spawn it with `execa` in the test and check the exit code.

**Comment by yaodingyd** [comment]
hmm, it doesn't work. I think there is always a parent node process, whether it's ava or the fixture, and it fails to kill the parent process.

**Comment by sindresorhus** [comment]
Even if you `detach` child process option?

**Comment by yaodingyd** [comment]
No on windows. Tried on both windows and Mac, always worked on Mac, never on windows

**Comment by yaodingyd** [comment]
I'm not using Ava (but it's the same) I just have these two files:

```javascript
// demo.js
const execa = require('execa');

(async () => {
	const result = await execa('node', ['./kill-node.js'], {detached: true});
	console.log(result);
})();
```
and 
```javascript
// kill-node.js
const fkill = require('..');
const processExists = require('process-exists');

const originalFkillPid = process.pid;
(async () => {
    if (process.platform === 'win32') {
        await fkill('node.exe');
    } else {
        await fkill('node');
    }

    process.exitCode = await processExists(originalFkillPid) ? 10 : 20;
})();

```
and run`node demo.js`

**Comment by sindresorhus** [comment]
Then I'm out of ideas...

**Comment by tomsotte** [comment]
@yaodingyd Hi, I've tried your scripts on Windows.

Given the processes tree:

```
'node.exe demo.js' 8948
|_ 'node.exe kill-node.js' 2760
   |_ 'taskkill /t /pid 8948' 9332
```

the `fkill` invocation on `kill-node.js` fails with the error:

> Error: Killing process node.exe failed: Command failed with exit code 128: taskkill /t /pid 8948

The error code 128 on Windows means that ["there are no child processes to wait for"](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-). I'm not sure how to interpret this error though, so I've made the assumption below.

If I understand correctly the problem in the solution proposed by this PR is that, the parent of the fkill invocation is node and gets globbed when trying to kill for every "node" process, resulting in killing the child processes and fkill itself as well.

If it is so, I guess we can use the processes list to find every parent from the fkill process up to the root process and exclude those, this way we won't kill fkill.
But we also won't be able use fkill inside a "node" process tree, we can only use fkill to kill other "node" process trees. But maybe it's not an important use case for fkill.

Let me know if you need more clarification or if I've missed the point somewhere.

**Comment by yaodingyd** [comment]
@sindresorhus seems like `ps-list` gives different output on linux with node 12.18:
Image 2020-07-13 at 2 57 42 PM
`ps.name` is not the title anymore which breaks the test.

I have test on process-exsits master which also breaks on linux node 12.18: https://travis-ci.org/github/yaodingyd/process-exists/builds/707740833

**Comment by tomsotte** [comment]
I've tried the solution you implemented and it works on Windows, this way we won't kill any of the process in the parent process tree of `fkill` on Windows 👍 

While doing trials I've spawned an external node.exe process and tried to kill it via `fkill('node.exe')`.
I've noticed that killing that node.exe process by `taskkill /t /pid` (the default way of fkill) seems to not work, and taskkill also suggest about using the `/f` (force kill) option.

**Comment by sindresorhus** [comment]
Closing as this is not moving forward.

**Pull request closed without merging**
