### PR TITLE
Make .EXE extension optional in windows

### LINKED ISSUE #1: Make extension optional on Windows?
Currently, you have to include the extension if you want to kill an application.

Eg. `fkill('notepad.exe')`

Would be nice if you just do `fkill('notepad')`.

If the user did `fkill('notepad')`, it could first try killing `notepad`, then `notepad.exe` if that didn't work.

Would love some thoughts on this from Windows users.

### PR DESCRIPTION
**Pull request by netrules**
Hello. Continuing from https://github.com/sindresorhus/fkill/pull/32 ... It's merger dropped development for a year and sindre closed it ... I am willing to split bounty, and finish what ever needs to be touched up in order to find a solution for https://github.com/sindresorhus/fkill/issues/1 ...

Not sure if regression tests are proper, also I hope error catching will serve the requested changes justice.

Thanks. Please let me know if I missed anything. Might also want to make a loop for **%PATHEXT%**?

Closes #1

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#1: Make extension optional on Windows?](https://issuehunt.io/repos/37784838/issues/1)
---
</details>

### CODE REVIEW

**Comment by netrules** [comment]
Hm. `npm test` passed on my container and TravisCI windows builds. Any clue if response is being cached and thus the build fail?

**Comment by sindresorhus** [comment]
Bump

**Comment by netrules** [comment]
> Bump

image
image
Accidentally kills itself now. No clue what is going on.

**Comment by sindresorhus** [comment]
Closing as this is not moving forward.

**Pull request closed without merging**
